export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_LOADING = 'SET_LOADING';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

export const FILTER_LOCATIONS = 'FILTER_LOCATIONS';
export const FILTER_CATEGORIES = 'FILTER_CATEGORIES';
export const FILTER_PLACES = 'FILTER_PLACES';
export const CLEAR_FILTER = 'CLEAR_FILTER,';

export const GET_LOCATIONS = 'GET_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
export const LOCATIONS_ERROR = 'LOCATIONS_ERROR';
export const SEARCH_LOCATIONS = 'SEARCH_LOCATIONS';
export const CURRENT_LOCATION = 'CURRENT_LOCATION';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
export const SEARCH_CATEGORIES = 'SEARCH_CATEGORIES';
export const CURRENT_CATEGORY = 'CURRENT_CATEGORY';

export const GET_PLACES = 'GET_PLACES';
export const ADD_PLACE = 'ADD_PLACE';
export const UPDATE_PLACE = 'UPDATE_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';
export const CLEAR_PLACES = 'CLEAR_PLACES';
export const PLACES_ERROR = 'PLACES_ERROR';
export const SEARCH_PLACES = 'SEARCH_PLACES';
export const CURRENT_PLACE = 'CURRENT_PLACE';
